version: '3.8'

services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-pg-container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    
  auth-service:
    build: ./AuthService
    container_name: auth-service-container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-db

  chat-service:
    build: ./chat-service
    container_name: chat-service-container
    ports:
      - "3333:3333"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@auth-db:5432/${DB_NAME}
    depends_on:
      - auth-db
      - auth-service

  media-service:
    build: ./media-service
    container_name: media-service-container
    ports:
      - "3004:3004"
    environment:
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  frontend:
    build: ./Frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_AUTH_API=http://localhost:8080
      - NEXT_PUBLIC_CHAT_API=http://localhost:3333
      - NEXT_PUBLIC_MEDIA_API=http://localhost:3004
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - auth-service
      - chat-service
      - media-service