version: "3.8"

services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-pg-container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    
  chat-db:
    image: postgres:16-alpine
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: ${CHAT_DB_USER}
      POSTGRES_PASSWORD: ${CHAT_DB_PASSWORD}
      POSTGRES_DB: ${CHAT_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${CHAT_DB_USER} -d ${CHAT_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - chat-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  social-db:
    image: postgres:16-alpine
    container_name: social-postgres
    restart: always
    environment:
      POSTGRES_USER: ${SOCIAL_DB_USER}
      POSTGRES_PASSWORD: ${SOCIAL_DB_PASSWORD}
      POSTGRES_DB: ${SOCIAL_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SOCIAL_DB_USER} -d ${SOCIAL_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - social-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # communication port
      - "15672:15672" # management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  auth-service:
    build: ./AuthService
    container_name: auth-service-container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - app-network

  chat-service:
    build: ./chat-service
    container_name: chat-service-container
    ports:
      - "3333:3333"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://${CHAT_DB_USER}:${CHAT_DB_PASSWORD}@chat-db:5432/${CHAT_DB_NAME}
      - AUTH_SERVICE_URL=http://auth-service:8080
    depends_on:
      - chat-db
      - auth-service
    networks:
      - app-network

  media-service:
    build: ./media-service
    container_name: media-service-container
    ports:
      - "3004:3004"
    environment:
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - app-network
    
  email-service:
    build: ./email-service
    container_name: email-service-container
    environment:
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672
      - GMAIL_PASS=${GMAIL_PASS}
      - GMAIL_USER=${GMAIL_USER}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  # frontend:
  #   build: ./Frontend
  #   container_name: frontend-container
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NEXT_PUBLIC_AUTH_API=http://localhost:8080
  #     - NEXT_PUBLIC_CHAT_API=http://localhost:3333
  #     - NEXT_PUBLIC_MEDIA_API=http://localhost:3004
  #   volumes:
  #     - ./Frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - auth-service
  #     - chat-service
  #     - media-service
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth-postgres-data:
  chat-postgres-data:
  social-postgres-data: