name: Email Service CI

on:
  push:
    paths:
      - 'email-service/**'
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: 'email-service/package-lock.json'

      - name: Install dependencies
        working-directory: ./email-service
        run: npm ci
      - name: Build Email Service
        working-directory: ./email-service
        run: npm run build